#ifndef _GUI_CONFIG_H__
#define _GUI_CONFIG_H__
#include <stdio.h>
#define Debug_P(fmt,...) printf(fmt)



typedef enum{
	MAIN_VIEW_ID,
	CONFIG_VIEW_ID,
	MANUAL_SET_VIEW_ID,
	SET_RAIN_MAIN_VIEW_ID,
	SET_RAIN_VALUE_VIEW_ID,
	SET_WATER_MAIN_VIEW_ID,
	HINT_VIEW_ID,
	UPLOAD_MANUAL_DATA_VIEW_ID,
	PARAMETER_SET_VIEW_ID,
	INSTALL_TEST_VIEW_ID,
	CLEAR_HISTORICAL_VIEW_ID,
    VERSION_VIEW_ID,
	SYS_REST_VIEW_ID,
	SCREEN_MAX_ID_NUM
}ScreenMember;
#define USER_CONFIG_MAX_GUI_NUM  SCREEN_MAX_ID_NUM

#endif//_GUI_CONFIG_H__

